Per #2106, not including 'shape' in the shared variable list causes a compilation error in GCC9.
data_plane_util.cc:262:36: error: "shape" not specified in enclosing "parallel"

However, including it causes a compilation error in GCC8!

data_plane_util.cc:257:38: error: 'shape' is predetermined 'shared' for 'shared'
    private(x, y, n_vld, n_thr, gp, v)

Try making "shape" non-const to see if that sidesteps the GCC8 issue.